# Generated by Django 4.2.15 on 2024-09-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=30)),
                ('obj_description', models.TextField(blank=True)),
                ('obj_address', models.CharField(max_length=100)),
                ('obj_coordinates', models.CharField(max_length=30)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('obj_status', models.CharField(choices=[('Черновик', 'Draft'), ('Сформирован', 'Formed'), ('Завершен', 'Completed'), ('Удален', 'Deleted'), ('Отклонен', 'Rejected')])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_objects', to='app.authuser')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderated_objects', to='app.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
                ('tag_description', models.TextField()),
                ('tag_image', models.CharField(max_length=100)),
                ('tag_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectsTagsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object_set', to='app.objects')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_set', to='app.tags')),
            ],
            options={
                'unique_together': {('object', 'tag')},
            },
        ),
    ]
